export const revalidate = 86400;
import { Metadata } from "next";
import Link from "next/link";
const SB=(process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "https://hnbjufmtmrhexmdrfubw.supabase.co");const SK=(process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY ?? (process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuYmp1Zm10bXJoZXhtZHJmdWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NzQ3MTksImV4cCI6MjA4MDM1MDcxOX0.-HzY9AayfTnAKAEwKNovWgFCxdYJkwEPptzR7DHj300"));
type L={id:string;name:string|null;slug:string|null;address1:string|null;short_description:string|null;logo_url:string|null;};
async function fj<T>(p:string):Promise<T>{const r=await fetch(`${SB}/rest/v1${p}`,{headers:{apikey:SK!,Authorization:`Bearer ${SK}`},next:{revalidate:86400}});if(!r.ok)return[]as unknown as T;return r.json();}
const LM:Record<string,{name:string;desc:string}>={
"near-wrigley-field":{name:"Wrigley Field",desc:"in Chicago's Wrigleyville neighborhood near Wrigley Field"},
"near-ohare":{name:"O'Hare Airport",desc:"near O'Hare International Airport on Chicago's Northwest Side"},
"near-navy-pier":{name:"Navy Pier",desc:"near Navy Pier in downtown Chicago"},
"near-magnificent-mile":{name:"the Magnificent Mile",desc:"near the Magnificent Mile on North Michigan Avenue"},
};
export async function generateMetadata({params}:{params:Promise<{landmark:string}>}):Promise<Metadata>{
const{landmark}=await params;const lm=LM[landmark]??{name:landmark,desc:"near this Chicago landmark"};
const url=`https://puffprice.com/cannabis/illinois/chicago/${landmark}`;
return{title:`Cannabis Dispensaries Near ${lm.name}, Chicago | PuffPrice`,description:`Find cannabis dispensaries ${lm.desc}. Licensed Illinois dispensaries, adults 21+.`,alternates:{canonical:url},openGraph:{title:`Dispensaries Near ${lm.name}, Chicago`,url,siteName:"PuffPrice",type:"website"},robots:{index:true,follow:true}};}
export default async function Page({params}:{params:Promise<{landmark:string}>}){
const{landmark}=await params;const lm=LM[landmark]??{name:landmark,desc:"near this Chicago landmark"};
const listings=await fj<L[]>(`/master_listings?city=ilike.Chicago&state=eq.IL&select=id,name,slug,address1,short_description,logo_url&order=name.asc&limit=20`);
return(<><style>{`*{box-sizing:border-box;margin:0;padding:0}.r{min-height:100vh;background:#f7f6f2;font-family:Georgia,serif}.nav{display:flex;justify-content:space-between;align-items:center;padding:16px 32px;background:#fff;border-bottom:1px solid #e8e5de;position:sticky;top:0;z-index:50}.nb{display:flex;align-items:center;gap:10px;text-decoration:none}.nd{width:10px;height:10px;border-radius:50%;background:#16a34a;display:inline-block}.nn{font-size:1.1rem;font-weight:700;color:#0f1f3d;letter-spacing:-.02em}.na{color:#16a34a}.nb2{font-size:.85rem;color:#6b7280;text-decoration:none;font-family:system-ui,sans-serif}.bc{padding:12px 32px;background:#fff;border-bottom:1px solid #f0ede6;font-size:.8rem;font-family:system-ui,sans-serif;color:#6b7280;display:flex;gap:8px}.bc a{color:#6b7280;text-decoration:none}.inner{max-width:900px;margin:0 auto;padding:32px 24px 64px}.lbl{font-size:.72rem;font-family:system-ui,sans-serif;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#16a34a;margin-bottom:12px}.h1{font-size:clamp(1.6rem,4vw,2.4rem);font-weight:700;color:#0f1f3d;letter-spacing:-.03em;line-height:1.15;margin-bottom:14px}.intro{font-size:.95rem;color:#374151;font-family:system-ui,sans-serif;line-height:1.7;margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid #e8e5de}.card{background:#fff;border-radius:14px;border:1px solid #e8e5de;padding:20px;display:flex;gap:16px;align-items:flex-start;text-decoration:none;margin-bottom:12px}.card:hover{border-color:#16a34a}.logo{width:52px;height:52px;border-radius:10px;border:1px solid #e8e5de;background:#f7f6f2;display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden;font-size:1.3rem;font-weight:700;color:#16a34a;font-family:Georgia,serif}.li{width:100%;height:100%;object-fit:contain;padding:5px}.info{flex:1}.nm{font-size:1rem;font-weight:700;color:#0f1f3d;font-family:Georgia,serif;margin-bottom:3px}.addr{font-size:.8rem;color:#6b7280;font-family:system-ui,sans-serif;margin-bottom:6px}.desc{font-size:.85rem;color:#374151;font-family:system-ui,sans-serif;line-height:1.5}.arr{font-size:1.2rem;color:#16a34a;flex-shrink:0;margin-top:4px}.cta{background:#0f1f3d;border-radius:16px;padding:28px;margin-top:40px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px}.ct{font-size:.95rem;font-weight:700;color:#fff}.cs{font-size:.8rem;color:#94a3b8;font-family:system-ui,sans-serif;margin-top:4px}.cb{background:#16a34a;color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;font-family:system-ui,sans-serif;font-weight:700;font-size:.85rem}.ft{background:#0f1f3d;padding:24px 32px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px}.fb{font-size:1rem;font-weight:700;color:#fff;font-family:Georgia,serif}.fn{font-size:.78rem;color:#475569;font-family:system-ui,sans-serif}@media(max-width:768px){.nav,.bc{padding:14px 20px}.inner{padding:20px 16px 48px}.cta{flex-direction:column}}`}</style>
<div className="r"><nav className="nav"><Link href="/" className="nb"><span className="nd"/><span className="nn">Directory<span className="na">Network</span></span></Link><Link href="/cannabis/illinois/chicago" className="nb2">← Chicago</Link></nav>
<div className="bc"><Link href="/">Home</Link><span>›</span><Link href="/cannabis/illinois">Illinois</Link><span>›</span><Link href="/cannabis/illinois/chicago">Chicago</Link><span>›</span><span style={{color:"#374151"}}>Near {lm.name}</span></div>
<div className="inner"><p className="lbl">Chicago Cannabis</p>
<h1 className="h1">Cannabis Dispensaries Near {lm.name}</h1>
<p className="intro">Licensed cannabis dispensaries {lm.desc}. Adults 21+ welcome, no medical card needed.</p>
{listings.length===0?(<p style={{color:"#6b7280",fontFamily:"system-ui,sans-serif"}}>No listings found. <Link href="/cannabis/illinois/chicago" style={{color:"#16a34a"}}>Browse all Chicago dispensaries →</Link></p>):listings.map(l=>(<Link key={l.id} href={`/l/${l.slug}`} className="card"><div className="logo">{l.logo_url?<img src={l.logo_url} alt={(l.name??"")+" logo"} className="li"/>:(l.name??"?").charAt(0)}</div><div className="info"><p className="nm">{l.name}</p>{l.address1&&<p className="addr">{l.address1}, Chicago, IL</p>}{l.short_description&&<p className="desc">{l.short_description}</p>}</div><span className="arr">→</span></Link>))}
<div className="cta"><div><p className="ct">Own a Chicago dispensary?</p><p className="cs">Get featured near {lm.name} for $49/month.</p></div><Link href="/get-listed" className="cb">Claim →</Link></div>
</div><footer className="ft"><span className="fb">Directory<span className="na">Network</span></span><span className="fn">© {new Date().getFullYear()} PuffPrice</span></footer></div></>);}
